baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

markup:
  goldmark:
    renderer:
      unsafe: true

title: "Integrative Physiology​​"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Yamada Lab​"
  description: "Integrative Physiology Lab​"
  icon: "images/logo-2.webp"
  images: 
    - "images/Main-image-2.webp"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    linkedin: 
      url: "https://www.linkedin.com/in/tatsuya-yamada-00b7331a0/"
      icon: "images/icons8-linkedin-128.webp"
    googlescholar: 
      url: "https://scholar.google.com/citations?user=YfkaXW8AAAAJ&hl=en&authuser=1"
      icon: "images/icons8-google-scholar-128.webp"
    ORCiD:
      url: "https://orcid.org/0000-0002-6906-9861"
      icon: "images/icons8-orcid-128.webp"
    Pubmed:
      url: "https://www.researchgate.net/profile/Tatsuya-Yamada-4"
      icon: "images/icons-researchgate-128.webp"

  location:
    - "1901 Vine st. Beadle Center, Lincoln, Nebraska 68588"
  contact:
    - "tyamada2”@”unl.edu​"
    - "4024726504"

  copyright: "© 2023 Yamada Lab All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Research"
      URL: "/#research"
      weight: 2

    - name: "Team"
      url: "/#team"
      weight: 3


    - name: "Publications"
      url: "/#publications"
      weight: 4

    - name: "News"
      url: "/#services"
      weight: 5

  buttons:
    - name: "Contact us"
      url: "/#cta"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Research"
      url: "/#research"
      weight: 2

    - name: "Team"
      url: "/#team"
      weight: 3

    - name: "Publications"
      url: "/#publications"
      weight: 4

    - name: "News"
      url: "/#services"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
