baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Integrative Physiology​​"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Yamada Lab​"
  description: "Integrative Physiology Lab​"
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    linkedin: "#"
    googlescholar: "#"
    ORCiD: "#"
    Pubmed: "#"

  location:
    - "1901 Vine st. Beadle Center, Lincoln, Nebraska 68588"
  contact:
    - "tyamada2”@”unl.edu​"
    - "4024726504"

  copyright: "© 2023 Yamada Lab All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Research"
      url: "/#"
      weight: 2

    - name: "Team"
      url: "/#"
      weight: 3

    - name: "News"
      url: "/#"
      weight: 4

    - name: "Publications"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Contact us"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Research"
      url: "/#"
      weight: 2

    - name: "Team"
      url: "/#"
      weight: 3

    - name: "News"
      url: "/#"
      weight: 4

    - name: "Publications"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
